// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Environment variables
const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const SUPABASE_ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY!;

// Detect if running on server (Node.js) or client (browser)
const isServer = typeof window === 'undefined';

// Choose appropriate key
const supabaseKey = isServer ? SUPABASE_SERVICE_ROLE_KEY : SUPABASE_ANON_KEY;

// Create Supabase client instance
export const supabase = createClient<Database>(SUPABASE_URL, supabaseKey);
